// Code generated by cmpgen; DO NOT EDIT.

package main

import (
	"fmt"
	"slices"
	"github.com/tmr232/cmpgen"
	"cmp"
)

func init() {
cmpgen.Register[Person](
		func (a, b Person) int {
			return cmp.Or(
				cmp.Compare(a.Name, b.Name),
				cmp.Compare(a.Age, b.Age),
			)
		},
		"Name","Age",
		)
}