name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # From https://github.com/golangci/golangci-lint-action
  golangci:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
      checks: write # for golangci/golangci-lint-action to annotate PRs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: "~1.23"
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "~1.23.0"
          check-latest: true

  test:
    strategy:
      matrix:
        os:
          - linux
          - mac
          - windows

        include:
          - os: linux
            OS_LABEL: ubuntu-latest

          - os: mac
            OS_LABEL: macos-latest

          - os: windows
            OS_LABEL: windows-latest

    runs-on: ${{ matrix.OS_LABEL }}
    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: "~1.23"
          check-latest: true
      - run: go test ./...
